(() => {
  "use strict";
  const STORAGE_KEY="three-pitch-state-v3";
  const NOTES=[["C",0],["C♯",1],["D",2],["D♯",3],["E",4],["F",5],["F♯",6],["G",7],["G♯",8],["A",9],["A♯",10],["B",11]].map(([name,value])=>({name,value}));
  const BASES=[["major","Major"],["minor","Minor"]].map(([id,label])=>({id,label}));
  const SHAPES=[["sus4","sus4"],["dim","Dim"],["aug","Aug"]].map(([id,label])=>({id,label}));
  const DECORATIONS=["6","7","maj7","dim7","add9","9","11","13"].map(id=>({id,label:id}));
  const DEFAULT={mode:"harmony",root:0,base:"major",shapes:[],decorations:[],melody:0,heard:[],previous:"",next:""};
  const $=id=>document.getElementById(id);
  const els={harmonyModeButton:$("harmonyModeButton"),detectModeButton:$("detectModeButton"),harmonyView:$("harmonyView"),detectView:$("detectView"),rootGrid:$("rootGrid"),baseGrid:$("baseGrid"),shapeGrid:$("shapeGrid"),decorationGrid:$("decorationGrid"),melodyGrid:$("melodyGrid"),chordName:$("chordName"),chordTones:$("chordTones"),upper:$("upperResultNote"),lower:$("lowerResultNote"),maybe:$("maybeNotes"),warning:$("melodyWarning"),heardGrid:$("heardNotesGrid"),heardCount:$("heardCount"),clearHeard:$("clearHeardButton"),previous:$("previousChord"),next:$("nextChord"),candidateList:$("candidateList")};
  let state=load();
  function load(){try{const r=JSON.parse(localStorage.getItem(STORAGE_KEY));return {...DEFAULT,...r,heard:Array.isArray(r?.heard)?r.heard:[],shapes:Array.isArray(r?.shapes)?r.shapes:[],decorations:Array.isArray(r?.decorations)?r.decorations:[]};}catch{return {...DEFAULT};}}
  function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
  function nn(v){return NOTES[((v%12)+12)%12].name;}
  function btn(label,cls,selected,fn,aria){const b=document.createElement("button");b.type="button";b.className=cls+(selected?" selected":"");b.textContent=label;b.setAttribute("aria-pressed",selected?"true":"false");if(aria)b.setAttribute("aria-label",aria);b.addEventListener("click",fn);return b;}
  function baseIntervalsFor(base,shapes){const sus4=shapes.includes("sus4"),dim=shapes.includes("dim"),aug=shapes.includes("aug");let third=sus4?5:dim?3:base==="minor"?3:4;let fifth=dim?6:aug?8:7;return [...new Set([0,third,fifth])];}
  function decorationIntervals(decs){const out=[];for(const id of decs){if(id==="6")out.push(9);if(id==="7")out.push(10);if(id==="maj7")out.push(11);if(id==="dim7")out.push(9);if(id==="add9")out.push(2);if(id==="9")out.push(10,2);if(id==="11")out.push(10,2,5);if(id==="13")out.push(10,2,5,9);}return [...new Set(out)];}
  function triadPitches(){return baseIntervalsFor(state.base,state.shapes).map(i=>(state.root+i)%12);}
  function extraPitches(){return decorationIntervals(state.decorations).map(i=>(state.root+i)%12);}
  function allPitches(){return [...new Set([...triadPitches(),...extraPitches()])];}
  function up(p,m){return(p-m+12)%12;} function down(p,m){return(m-p+12)%12;}
  function directional(triad,dir){const d=dir==="up"?up:down;return triad.map(p=>({p,d:d(p,state.melody)})).filter(x=>x.d>0).sort((a,b)=>a.d-b.d||a.p-b.p)[0]?.p??triad[0];}
  function chordLabel(){let s=nn(state.root),sus=state.shapes.includes("sus4"),dim=state.shapes.includes("dim"),aug=state.shapes.includes("aug");if(dim&&!sus)s+=state.base==="minor"?"m♭5":"dim";else if(aug&&!sus)s+=state.base==="minor"?"m♯5":"aug";else{if(state.base==="minor")s+="m";if(sus)s+="sus4";if(dim)s+="♭5";if(aug)s+="♯5";}["6","7","maj7","dim7","add9","9","11","13"].forEach(id=>{if(state.decorations.includes(id))s+=id;});return s;}
  function renderHarmonySelectors(){const triad=new Set(triadPitches()),extras=new Set(extraPitches());els.rootGrid.innerHTML="";NOTES.forEach(n=>els.rootGrid.appendChild(btn(n.name,"note-button",state.root===n.value,()=>{state.root=n.value;update();})));els.baseGrid.innerHTML="";BASES.forEach(x=>els.baseGrid.appendChild(btn(x.label,"choice-button",state.base===x.id,()=>{state.base=x.id;update();})));els.shapeGrid.innerHTML="";SHAPES.forEach(x=>els.shapeGrid.appendChild(btn(x.label,"choice-button",state.shapes.includes(x.id),()=>toggleShape(x.id))));els.decorationGrid.innerHTML="";DECORATIONS.forEach(x=>els.decorationGrid.appendChild(btn(x.label,"decoration-button",state.decorations.includes(x.id),()=>toggleDecoration(x.id))));els.melodyGrid.innerHTML="";NOTES.forEach(n=>{let cls="note-button";if(triad.has(n.value))cls+=" chord-tone";else if(extras.has(n.value))cls+=" decor-tone";if(state.melody===n.value&&!triad.has(n.value)&&!extras.has(n.value))cls+=" invalid-selected";els.melodyGrid.appendChild(btn(n.name,cls,state.melody===n.value,()=>{state.melody=n.value;update();}));});}
  function toggleShape(id){const s=new Set(state.shapes);if(s.has(id))s.delete(id);else{if(id==="dim")s.delete("aug");if(id==="aug")s.delete("dim");s.add(id);}state.shapes=[...s];update();}
  function toggleDecoration(id){const s=new Set(state.decorations);if(s.has(id))s.delete(id);else{if(["7","maj7","dim7"].includes(id))["7","maj7","dim7"].forEach(x=>s.delete(x));s.add(id);}state.decorations=[...s];update();}
  function renderHarmonyResult(){const triad=[...new Set(triadPitches())],all=allPitches(),upper=directional(triad,"up"),lower=directional(triad,"down");els.chordName.textContent=chordLabel();els.chordTones.textContent=all.map(nn).join(" · ");els.upper.textContent=nn(upper);els.lower.textContent=nn(lower);els.warning.hidden=all.includes(state.melody);const alternatives=all.filter(p=>p!==upper&&p!==lower).sort((a,b)=>up(a,state.root)-up(b,state.root));els.maybe.innerHTML="";if(!alternatives.length){const x=document.createElement("span");x.className="maybe-empty";x.textContent="—";els.maybe.appendChild(x);}else alternatives.forEach(p=>{const x=document.createElement("span");x.className="maybe-note";x.textContent=nn(p);els.maybe.appendChild(x);});}

  const QUALITY_LIBRARY=[
    {suffix:"",quality:"Major",ints:[0,4,7],weight:3},{suffix:"m",quality:"Minor",ints:[0,3,7],weight:3},{suffix:"sus4",quality:"sus4",ints:[0,5,7],weight:2},{suffix:"dim",quality:"Dim",ints:[0,3,6],weight:2},{suffix:"aug",quality:"Aug",ints:[0,4,8],weight:1.6},
    {suffix:"6",quality:"6",ints:[0,4,7,9],weight:1.5},{suffix:"7",quality:"7",ints:[0,4,7,10],weight:2.3},{suffix:"maj7",quality:"maj7",ints:[0,4,7,11],weight:2.1},{suffix:"m7",quality:"m7",ints:[0,3,7,10],weight:2.3},{suffix:"m7♭5",quality:"m7♭5",ints:[0,3,6,10],weight:1.5},{suffix:"dim7",quality:"dim7",ints:[0,3,6,9],weight:1.3},{suffix:"add9",quality:"add9",ints:[0,2,4,7],weight:1.4}
  ];
  const CHORDS=[];for(let root=0;root<12;root++)for(const q of QUALITY_LIBRARY){CHORDS.push({root,name:nn(root)+q.suffix,quality:q.quality,tones:[...new Set(q.ints.map(i=>(root+i)%12))],weight:q.weight});}
  function chordOptionList(){const options=['<option value="">指定なし</option>'];for(const c of CHORDS.filter(c=>["Major","Minor","7","maj7","m7","sus4","Dim","Aug"].includes(c.quality)))options.push(`<option value="${c.name}">${c.name}</option>`);return options.join("");}
  function renderDetectSelectors(){els.heardGrid.innerHTML="";NOTES.forEach(n=>els.heardGrid.appendChild(btn(n.name,"note-button",state.heard.includes(n.value),()=>{const s=new Set(state.heard);s.has(n.value)?s.delete(n.value):s.add(n.value);state.heard=[...s].sort((a,b)=>a-b);update();})));els.heardCount.textContent=`${state.heard.length}音選択`;}
  function findChord(name){return CHORDS.find(c=>c.name===name)||null;}
  function rootMotionScore(from,to){if(!from||!to)return 0;const move=(to.root-from.root+12)%12;if(move===5||move===7)return 8;if(move===2||move===10)return 5;if(move===0)return 2;if(move===1||move===11)return 1;return 3;}
  function commonToneScore(a,b){if(!a||!b)return 0;return a.tones.filter(t=>b.tones.includes(t)).length*2;}
  function scoreCandidate(c){const heard=state.heard,matched=heard.filter(n=>c.tones.includes(n)).length,missingHeard=heard.length-matched,extra=c.tones.filter(n=>!heard.includes(n)).length;let score=matched*28-missingHeard*34-extra*7+c.weight;if(heard.length&&matched===heard.length)score+=24;if(heard.length===c.tones.length&&extra===0&&missingHeard===0)score+=25;const prev=findChord(state.previous),next=findChord(state.next);score+=rootMotionScore(prev,c)+commonToneScore(prev,c);score+=rootMotionScore(c,next)+commonToneScore(c,next);return {score,matched,extra,prev,next};}
  function renderCandidates(){els.candidateList.innerHTML="";if(state.heard.length<2){els.candidateList.innerHTML='<div class="empty-candidates">聞こえた音を2音以上選ぶと候補が表示されます。</div>';return;}const ranked=CHORDS.map(c=>({c,...scoreCandidate(c)})).filter(x=>x.matched>=Math.min(2,state.heard.length)).sort((a,b)=>b.score-a.score||a.extra-b.extra||a.c.name.localeCompare(b.c.name)).slice(0,12);if(!ranked.length){els.candidateList.innerHTML='<div class="empty-candidates">一致する候補がありません。</div>';return;}ranked.forEach((x,i)=>{const row=document.createElement("div");row.className="candidate-row";const coverage=`${x.matched}/${state.heard.length}音一致`;const context=(state.previous||state.next)?"前後進行を加味":"音構成で判定";row.innerHTML=`<div class="candidate-rank">${i+1}</div><div class="candidate-name">${x.c.name}</div><div class="candidate-tones">${x.c.tones.map(nn).join(" · ")}</div><div class="candidate-score">${Math.max(1,Math.round(x.score))}</div><div class="candidate-reason">${coverage} / ${context}</div>`;els.candidateList.appendChild(row);});}
  function setMode(mode){state.mode=mode;els.harmonyModeButton.classList.toggle("active",mode==="harmony");els.detectModeButton.classList.toggle("active",mode==="detect");els.harmonyView.classList.toggle("active",mode==="harmony");els.detectView.classList.toggle("active",mode==="detect");save();}
  function update(){save();renderHarmonySelectors();renderHarmonyResult();renderDetectSelectors();renderCandidates();}
  els.harmonyModeButton.addEventListener("click",()=>setMode("harmony"));els.detectModeButton.addEventListener("click",()=>setMode("detect"));els.clearHeard.addEventListener("click",()=>{state.heard=[];update();});
  els.previous.innerHTML=chordOptionList();els.next.innerHTML=chordOptionList();els.previous.value=state.previous;els.next.value=state.next;els.previous.addEventListener("change",()=>{state.previous=els.previous.value;update();});els.next.addEventListener("change",()=>{state.next=els.next.value;update();});
  setMode(state.mode);update();
})();